import sys

fail = False

if fail:
    print("TRIAL FAIL")
    sys.exit(1)
